# Generated by Django 4.1.6 on 2023-04-13 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Carousel',
                    fields=[
                        ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('name', models.CharField(db_index=True, max_length=250)),
                        ('slug', models.SlugField(max_length=250)),
                        ('active', models.BooleanField(default=False)),
                        ('image', models.ImageField(upload_to='images/')),
                    ],
                    options={
                        'db_table': 'shop_carousel',
                    },
                )
            ],
            database_operations=[],
        )

    ]
