# Generated by Django 4.1.6 on 2023-05-09 12:49

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='about',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intro', ckeditor.fields.RichTextField()),
                ('vision', ckeditor.fields.RichTextField()),
                ('mission', ckeditor.fields.RichTextField()),
                ('product_range', ckeditor.fields.RichTextField()),
                ('company_details', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
