# Generated by Django 4.1.6 on 2023-02-08 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carousel',
            name='is_active',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='never', max_length=50),
        ),
    ]
