# Generated by Django 4.1.6 on 2023-02-08 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_carousel_is_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carousel',
            options={'verbose_name_plural': 'carousels'},
        ),
    ]
