# Generated by Django 4.1.6 on 2023-02-08 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_carousel_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carousel',
            name='slug',
            field=models.SlugField(max_length=250),
        ),
    ]
