# Generated by Django 4.1.6 on 2023-02-16 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_alter_carousel_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carousel',
            name='is_active',
        ),
        migrations.AddField(
            model_name='carousel',
            name='active',
            field=models.BooleanField(default=False),
        ),
    ]
