# Generated by Django 4.1.6 on 2023-02-20 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_carousel_is_active_carousel_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(db_index=True, max_length=250)),
                ('brand_slug', models.SlugField(max_length=250)),
                ('brand_description', models.TextField(max_length=1200)),
                ('brand_active', models.BooleanField(default=False)),
                ('brand_image', models.ImageField(upload_to='images/brands/')),
            ],
            options={
                'verbose_name_plural': 'brands',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(db_index=True, max_length=250)),
                ('category_slug', models.SlugField(max_length=250)),
                ('category_description', models.TextField(max_length=1200)),
                ('category_active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(db_index=True, max_length=250)),
                ('product_slug', models.SlugField(max_length=250)),
                ('product_description', models.TextField(max_length=1200)),
                ('product_active', models.BooleanField(default=False)),
                ('product_image', models.ImageField(upload_to='images/products/')),
                ('product_brand', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_brand', to='shop.brand')),
                ('product_category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_category', to='shop.category')),
            ],
            options={
                'verbose_name_plural': 'products',
            },
        ),
        migrations.AddField(
            model_name='brand',
            name='brand_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brand_category', to='shop.category'),
        ),
    ]
