# Generated by Django 4.1.6 on 2023-04-13 03:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_brand_category_product_brand_brand_category'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.DeleteModel(
                    name='Carousel',
                ),
            ],
            # You want to reuse the table, so don't drop it
            database_operations=[],
        )
    ]
